# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2' # or newest one

gem 'awesome_print'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'devise_token_auth', '~> 1.1.2'
gem 'mjml-rails', '4.3.0'
gem 'pg', '>= 0.18', '< 2.0'
gem 'pry-rails'
gem 'puma'
gem 'pundit'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 5.2.5'
gem 'rails-i18n', '~> 5.1.3'
gem 'sidekiq', '~> 6.0'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails', '~> 2.7.4'
  gem 'factory_bot_rails'
  gem 'rspec_junit_formatter', '~> 0.4.1'
  gem 'rspec-rails', '~> 3.7'
  gem 'rubocop', '~> 1.21.0', require: false
  gem 'rubocop-rspec', '~> 2.4.0', require: false
  gem 'rubycritic', require: false
  gem 'webmock', '~> 3.6.0'
end

group :development do
  gem 'letter_opener'
  gem 'listen'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'simplecov', '~> 0.21.0', require: false
  gem 'simplecov-lcov', require: false
  gem 'super_diff', require: 'super_diff/rspec-rails'
  gem 'undercover'
  gem 'undercover-checkstyle'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
